# Generated by Django 3.1.7 on 2021-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='participants',
        ),
        migrations.AddField(
            model_name='podcast',
            name='participants',
            field=models.ManyToManyField(default=None, to='audio_api.Podcast'),
        ),
    ]
